### ISSUE TITLE
Windows PIP install problems

### ISSUE THREAD

**Issue by golyalpha** [pipermerriam/ethereum-alarm-client#10]
I have a problem where pip refuses to install the client on my Windows PC.

Error from cmdline:
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\radekg~1\\appdata\\local\\temp\\pip-build-fxjmqg\\secp256k1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\radekg~1\appdata\local\temp\pip-drfrlr-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\radekg~1\appdata\local\temp\pip-build-fxjmqg\secp256k1\

It's something regarding secp256k1, aparently doing some funny linux-only stuff, like running bash scripts (Seriously? Although, I do have bash installed in path so...)

**Comment by pipermerriam** [comment]
What you're seeing is the install process for the python library `secp256k1` attempting to compile itself against the related system dependency.

Currently this project depends on `populus` which depends on `pyethereum` which requires a few system dependencies (`secp256k1` being one of them).

Currently this codebase isn't tested or supported on windows based platforms.  I'm open to having support for windows added but I personally don't have the tools to test on that platform, nor do I have the time to dedicate to proper support for it.

I'm happy however to try and help you trouble shoot any issues you run into.  This one looks like you need the system dependency installed which I think you may have figured out already.

**Comment by golyalpha** [comment]
I've actually been reading up on it, and it seems that the problem is that it is trying to determine which compiler to use using bash script, which fails, and they have no catch for it so it could assume it's a windows machine, although there is a way to make it work, it requires me to have access to the code of the dependency. Reportedly, it works just by changing one line, which makes it compile windows only. I'll let you know, in case I find any other problems when I resolve this one.

**Comment by golyalpha** [comment]
I think I resolved it. For windows you use 

> secp256k1-transient

 instead of 

> secp256k1
